
default: all

CC = gcc

CONFIG += ansi
CONFIG += debug

CxPath = ../cx
BinPath = ../bin
BldPath = exc

ExeList = aperiodic leadercard count-search
#ExeList += polystep
#ExeList += bddtest
Deps := $(ExeList)
ExeList := $(addprefix $(BinPath)/,$(ExeList))
Objs = $(addprefix $(BldPath)/,$(addsuffix .o,$(Deps)))

include $(CxPath)/include.mk

CXXFLAGS += $(CFLAGS)

all: $(ExeList)

$(call binexe,bddtest): $(BldPath)/bddtest.o $(CxStdObjs)
	$(CC) $(CFLAGS) -o $@ $^ -lbdd

$(call binexe,count-search): $(BldPath)/count-search.o $(CxStdObjs)
	$(CC) $(CFLAGS) -o $@ $^

$(call binexe,polystep): $(BldPath)/polystep.o $(CxStdObjs)
	$(CC) $(CFLAGS) -o $@ $^ -lgmp

$(call binexe,aperiodic): $(BldPathCXX)/aperiodic.o $(CxStdObjs)
	$(CXX) $(CXXFLAGS) -o $@ $^

$(call binexe,leadercard): $(BldPathCXX)/leadercard.o
	$(CXX) $(CXXFLAGS) -o $@ $^

.PHONY: clean
clean:
	rm -fr $(PfxBldPath)
	rm -f $(ExeList)

